---
- name: Installing FirewallD
  hosts: all
  become: yes
  tasks:
      - name: Installing firewalld 
        apt:
          name: firewalld
          state: "present"
          update_cache: true
      - name: Starting the service
        service: 
          name: firewalld
          state: started
          enabled: yes 

- name: Installing and starting MariaDB
  hosts: all
  become: yes 
  vars: 
    packages:
      - mariadb-server
      - python3-pip
      - libmysqlclient-dev   
  tasks:
    - name: Installing MariaDB and Pre-Requisites
      package:
        name: '{{ item }}'
        state: "present"
        update_cache: true 
      loop: '{{ packages}}'
    - name: Installing mysqlclient 
      pip: 
        executable: pip3 
        name: mysqlclient
        state: "present"

    - name: Starting MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes  

    - name: Configuring firewalld for MariaDB 
      firewalld: 
        permanent: true
        zone: public
        port: 3306/tcp
        state: "enabled"
        immediate: true


- name: Configuring the Database
  hosts: all 
  become: yes 
  tasks:
    - name: Create the database
      mysql_db:
        name: ecomdb
        state: present

    - name: Create the user
      mysql_user: 
        name: ecomuser
        password: "ecompassword"
        priv: '*.*:ALL'
        state: present

    - name: Copying the SQL script
      copy: 
        dest: "~/"
        src: "db-load-script.sql"

    - name: Executing the SQL script
      mysql_db:
        chdir: "~/"
        login_user: ecomuser
        login_password: "ecompassword"
        name: ecomdb
        state: import
        target: "db-load-script.sql"
  

## On the WEB servers 
- name: Installing the WEB server 
  hosts: all 
  become: yes
  vars: 
    packages: 
      - apache2
      - php 
      - php-mysql
      - git 

  tasks: 
    - name: Configuring firewalld for the WEB Server 
      firewalld: 
        permanent: true
        zone: public
        port: 80/tcp
        state: "enabled"
        immediate: true

    - name: installing the required packages for the Server
      apt: 
        name:  '{{ item }}'
        state: "present"
        update_cache: true
      loop: 
        - '{{ packages }}'

    - name: Starting the WEB server
      service: 
        name: apache2
        state: started
        enabled: yes

    - name: Replace index.html with index.php 
      replace:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: 'index.html'
        replace: 'index.php'

    - name: Installing the code 
      git: 
        repo: "https://github.com/kodekloudhub/learning-app-ecommerce.git"
        dest: "/var/www/html/"
        clone: yes 
        force: true

    - name: Updating the code 
      replace: 
        path: /var/www/html/index.php
        regexp: '172.20.1.101'
        # ip of the database server
        replace: 'localhost'
      
