---
- name: Installing FirewallD
  hosts: all
  become: yes
  tasks:
      - name: Installing firewalld 
        apt:
          name: firewalld
          state: "present"
          update_cache: true
      - name: Starting the service
        service: 
          name: firewalld
          state: started
          enabled: yes 

- name: Installing and starting MariaDB
  hosts: all 
  become: yes 
  tasks:
    - name: Installing MariaDB
      apt:
        name: mariadb-server
        state: "present"
        update_cache: true 
    - name: Starting MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes  
    - name: Configuring firewalld for MariaDB 
      firewalld: 
        permanent: true
        zone: public
        port: 3306/tcp
        state: "enabled"
        immediate: true

# Le module mysql a besoin de mysqlclient qui lui meme a besoin de libmysqlclient-dev 
# surement à regrouper avec l'installation de MariaDB via APT 
- name: Configuring the Database
  hosts: all 
  become: yes 
  tasks:
    - name: Installing pip3
      apt: 
        name: python3-pip
        state: "present"
        update_cache: true
    - name: Installing libmysqlclient-dev
      apt: 
        name: libmysqlclient-dev
        state: "present"
        update_cache: yes
    - name: Installing mysqlclient 
      pip: 
        executable: pip3 
        name: mysqlclient
        state: "present"
    - name: Create the database
      mysql_db:
        name: ecomdb
        state: present 
    - name: Create the user
      mysql_user: 
        name: ecomuser
        password: "ecompassword"
        priv: '*.*:ALL'
        state: present
    - name: Copying the SQL script
      copy: 
        dest: "~/"
        src: "db-load-script.sql"
    - name: Executing the SQL script
      mysql_db:
        chdir: "~/"
        login_user: ecomuser
        login_password: "ecompassword"
        login_host: localhost
        name: ecomdb
        state: import
        target: "db-load-script.sql"
  

## sur le serveur WEB 
- name: Installing the WEB server 
  hosts: all 
  become: yes
  vars: 
    packages: 
      - apache2
      - php 
      - php-mysql
  tasks: 
    - name: Configuring firewalld for the WEB Server 
      firewalld: 
        permanent: true
        zone: public
        port: 80/tcp
        state: "enabled"
        immediate: true

    - name: installing the required packages for the Server
      apt: 
        name:  '{{ item }}'
        state: "present"
        update_cache: true
      loop: 
        - '{{ packages }}'
    - name: Starting the WEB server
      service: 
        name: apache2
        state: started
        enabled: yes

    - name: Replace index.html with index.php 
      replace:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: 'index.html'
        replace: 'index.php'

    - name: Installing Git 
      apt: 
        name: git 
        state: "present"
    - name: Installing the code 
      git: 
        repo: "https://github.com/kodekloudhub/learning-app-ecommerce.git"
        dest: "/var/www/html/"
        clone: yes 
        force: true

    - name: Updating the code 
      replace: 
        path: /var/www/html/index.php
        regexp: '172.20.1.101'
        replace: 'localhost'
      
